from pytest import fixture

@fixture
def prokerala_natal_planet_position():
    return {'data': {'angles': [{'degree': 0.4464058726933331,
                      'house_number': 1,
                      'id': 100,
                      'is_retrograde': False,
                      'longitude': 300.44640587269333,
                      'name': 'Ascendant',
                      'zodiac': {'id': 10,
                                 'lord': {'id': 6, 'name': 'Saturn'},
                                 'name': 'Aquarius'}},
                     {'degree': 14.92698654990852,
                      'house_number': 4,
                      'id': 107,
                      'is_retrograde': False,
                      'longitude': 44.92698654990852,
                      'name': 'Nadir',
                      'zodiac': {'id': 1,
                                 'lord': {'id': 3, 'name': 'Venus'},
                                 'name': 'Taurus'}},
                     {'degree': 0.4464058726933331,
                      'house_number': 7,
                      'id': 108,
                      'is_retrograde': False,
                      'longitude': 120.44640587269333,
                      'name': 'Descendant',
                      'zodiac': {'id': 4,
                                 'lord': {'id': 0, 'name': 'Sun'},
                                 'name': 'Leo'}},
                     {'degree': 14.92698654990852,
                      'house_number': 10,
                      'id': 109,
                      'is_retrograde': False,
                      'longitude': 224.92698654990852,
                      'name': 'Mid Heaven',
                      'zodiac': {'id': 7,
                                 'lord': {'id': 4, 'name': 'Mars'},
                                 'name': 'Scorpio'}}],
          'aspects': [{'aspect': {'id': 3, 'name': 'Semi Square'},
                       'orb': 1.898498696249078,
                       'planet_one': {'id': 0, 'name': 'Sun'},
                       'planet_two': {'id': 3, 'name': 'Venus'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 3.710459997461328,
                       'planet_one': {'id': 0, 'name': 'Sun'},
                       'planet_two': {'id': 6, 'name': 'Saturn'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 0.27775220682786994,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 7, 'name': 'Uranus'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 3.384245251961829,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 8, 'name': 'Neptune'}},
                      {'aspect': {'id': 0, 'name': 'Conjunction'},
                       'orb': 7.1512224026454305,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 9, 'name': 'Pluto'}},
                      {'aspect': {'id': 2, 'name': 'Square'},
                       'orb': 4.910810204059771,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 15, 'name': 'Chiron'}},
                      {'aspect': {'id': 2, 'name': 'Square'},
                       'orb': 3.3511286300645224,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 105, 'name': 'Lilith'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 6.963656784122691,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}},
                      {'aspect': {'id': 0, 'name': 'Conjunction'},
                       'orb': 6.53282642813889,
                       'planet_one': {'id': 1, 'name': 'Moon'},
                       'planet_two': {'id': 100, 'name': 'Ascendant'}},
                      {'aspect': {'id': 1, 'name': 'Opposition'},
                       'orb': 6.654515509413017,
                       'planet_one': {'id': 2, 'name': 'Mercury'},
                       'planet_two': {'id': 5, 'name': 'Jupiter'}},
                      {'aspect': {'id': 2, 'name': 'Square'},
                       'orb': 5.3459072337328735,
                       'planet_one': {'id': 2, 'name': 'Mercury'},
                       'planet_two': {'id': 6, 'name': 'Saturn'}},
                      {'aspect': {'id': 2, 'name': 'Square'},
                       'orb': 7.42784665448977,
                       'planet_one': {'id': 2, 'name': 'Mercury'},
                       'planet_two': {'id': 8, 'name': 'Neptune'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 0.8672088015318593,
                       'planet_one': {'id': 2, 'name': 'Mercury'},
                       'planet_two': {'id': 15, 'name': 'Chiron'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 0.6924727724634181,
                       'planet_one': {'id': 2, 'name': 'Mercury'},
                       'planet_two': {'id': 105, 'name': 'Lilith'}},
                      {'aspect': {'id': 2, 'name': 'Square'},
                       'orb': 4.076282269354806,
                       'planet_one': {'id': 3, 'name': 'Venus'},
                       'planet_two': {'id': 7, 'name': 'Uranus'}},
                      {'aspect': {'id': 7, 'name': 'Semi Sextile'},
                       'orb': 0.4142848105651069,
                       'planet_one': {'id': 3, 'name': 'Venus'},
                       'planet_two': {'id': 8, 'name': 'Neptune'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 7.1496586925914585,
                       'planet_one': {'id': 3, 'name': 'Venus'},
                       'planet_two': {'id': 105, 'name': 'Lilith'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 4.6200982436520235,
                       'planet_one': {'id': 4, 'name': 'Mars'},
                       'planet_two': {'id': 8, 'name': 'Neptune'}},
                      {'aspect': {'id': 1, 'name': 'Opposition'},
                       'orb': 0.8531210929684221,
                       'planet_one': {'id': 4, 'name': 'Mars'},
                       'planet_two': {'id': 9, 'name': 'Pluto'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 1.0406867114911478,
                       'planet_one': {'id': 4, 'name': 'Mars'},
                       'planet_two': {'id': 103, 'name': 'True North Node'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 1.040686711491162,
                       'planet_one': {'id': 4, 'name': 'Mars'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}},
                      {'aspect': {'id': 1, 'name': 'Opposition'},
                       'orb': 1.471517067474963,
                       'planet_one': {'id': 4, 'name': 'Mars'},
                       'planet_two': {'id': 100, 'name': 'Ascendant'}},
                      {'aspect': {'id': 2, 'name': 'Square'},
                       'orb': 1.3086082756801716,
                       'planet_one': {'id': 5, 'name': 'Jupiter'},
                       'planet_two': {'id': 6, 'name': 'Saturn'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 7.346988281876435,
                       'planet_one': {'id': 5, 'name': 'Jupiter'},
                       'planet_two': {'id': 105, 'name': 'Lilith'}},
                      {'aspect': {'id': 9, 'name': 'Quintile'},
                       'orb': 0.338226303936338,
                       'planet_one': {'id': 5, 'name': 'Jupiter'},
                       'planet_two': {'id': 103, 'name': 'True North Node'}},
                      {'aspect': {'id': 3, 'name': 'Semi Square'},
                       'orb': 1.5407310389062445,
                       'planet_one': {'id': 6, 'name': 'Saturn'},
                       'planet_two': {'id': 9, 'name': 'Pluto'}},
                      {'aspect': {'id': 10, 'name': 'Bi Quintile'},
                       'orb': 0.03838000619629156,
                       'planet_one': {'id': 6, 'name': 'Saturn'},
                       'planet_two': {'id': 105, 'name': 'Lilith'}},
                      {'aspect': {'id': 3, 'name': 'Semi Square'},
                       'orb': 0.9223350643997037,
                       'planet_one': {'id': 6, 'name': 'Saturn'},
                       'planet_two': {'id': 100, 'name': 'Ascendant'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 3.661997458789699,
                       'planet_one': {'id': 7, 'name': 'Uranus'},
                       'planet_two': {'id': 8, 'name': 'Neptune'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 7.4289746094733005,
                       'planet_one': {'id': 7, 'name': 'Uranus'},
                       'planet_two': {'id': 9, 'name': 'Pluto'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 7.241408990950575,
                       'planet_one': {'id': 7, 'name': 'Uranus'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 6.81057863496676,
                       'planet_one': {'id': 7, 'name': 'Uranus'},
                       'planet_two': {'id': 100, 'name': 'Ascendant'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 3.7669771506836014,
                       'planet_one': {'id': 8, 'name': 'Neptune'},
                       'planet_two': {'id': 9, 'name': 'Pluto'}},
                      {'aspect': {'id': 0, 'name': 'Conjunction'},
                       'orb': 3.5794115321608615,
                       'planet_one': {'id': 8, 'name': 'Neptune'},
                       'planet_two': {'id': 103, 'name': 'True North Node'}},
                      {'aspect': {'id': 1, 'name': 'Opposition'},
                       'orb': 3.5794115321608615,
                       'planet_one': {'id': 8, 'name': 'Neptune'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 3.1485811761770606,
                       'planet_one': {'id': 8, 'name': 'Neptune'},
                       'planet_two': {'id': 100, 'name': 'Ascendant'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 0.1875656185227399,
                       'planet_one': {'id': 9, 'name': 'Pluto'},
                       'planet_two': {'id': 103, 'name': 'True North Node'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 0.1875656185227399,
                       'planet_one': {'id': 9, 'name': 'Pluto'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}},
                      {'aspect': {'id': 0, 'name': 'Conjunction'},
                       'orb': 0.6183959745065408,
                       'planet_one': {'id': 9, 'name': 'Pluto'},
                       'planet_two': {'id': 100, 'name': 'Ascendant'}},
                      {'aspect': {'id': 1, 'name': 'Opposition'},
                       'orb': 1.5596815739952774,
                       'planet_one': {'id': 15, 'name': 'Chiron'},
                       'planet_two': {'id': 105, 'name': 'Lilith'}},
                      {'aspect': {'id': 1, 'name': 'Opposition'},
                       'orb': 0.0,
                       'planet_one': {'id': 103, 'name': 'True North Node'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}},
                      {'aspect': {'id': 6, 'name': 'Sextile'},
                       'orb': 0.43083035598380093,
                       'planet_one': {'id': 100, 'name': 'Ascendant'},
                       'planet_two': {'id': 103, 'name': 'True North Node'}},
                      {'aspect': {'id': 5, 'name': 'Trine'},
                       'orb': 0.43083035598380093,
                       'planet_one': {'id': 100, 'name': 'Ascendant'},
                       'planet_two': {'id': 104, 'name': 'True South Node'}}],
          'declinations': [{'aspect': {'id': 11, 'name': 'Parallel'},
                            'orb': 1.0567835241876828,
                            'planet_one': {'id': 0, 'name': 'Sun'},
                            'planet_two': {'id': 2, 'name': 'Mercury'}},
                           {'aspect': {'id': 12, 'name': 'Contra Parallel'},
                            'orb': 0.5470176766661012,
                            'planet_one': {'id': 0, 'name': 'Sun'},
                            'planet_two': {'id': 4, 'name': 'Mars'}},
                           {'aspect': {'id': 12, 'name': 'Contra Parallel'},
                            'orb': 1.2108322449107476,
                            'planet_one': {'id': 0, 'name': 'Sun'},
                            'planet_two': {'id': 5, 'name': 'Jupiter'}},
                           {'aspect': {'id': 11, 'name': 'Parallel'},
                            'orb': 0.11591753139383698,
                            'planet_one': {'id': 0, 'name': 'Sun'},
                            'planet_two': {'id': 9, 'name': 'Pluto'}},
                           {'aspect': {'id': 12, 'name': 'Contra Parallel'},
                            'orb': 0.15404872072306475,
                            'planet_one': {'id': 2, 'name': 'Mercury'},
                            'planet_two': {'id': 5, 'name': 'Jupiter'}},
                           {'aspect': {'id': 11, 'name': 'Parallel'},
                            'orb': 1.1727010555815198,
                            'planet_one': {'id': 2, 'name': 'Mercury'},
                            'planet_two': {'id': 9, 'name': 'Pluto'}},
                           {'aspect': {'id': 11, 'name': 'Parallel'},
                            'orb': 1.7578499215768488,
                            'planet_one': {'id': 4, 'name': 'Mars'},
                            'planet_two': {'id': 5, 'name': 'Jupiter'}},
                           {'aspect': {'id': 12, 'name': 'Contra Parallel'},
                            'orb': 0.43110014527226426,
                            'planet_one': {'id': 4, 'name': 'Mars'},
                            'planet_two': {'id': 9, 'name': 'Pluto'}},
                           {'aspect': {'id': 12, 'name': 'Contra Parallel'},
                            'orb': 1.3267497763045846,
                            'planet_one': {'id': 5, 'name': 'Jupiter'},
                            'planet_two': {'id': 9, 'name': 'Pluto'}}],
          'houses': [{'end_cusp': {'degree': 8.13636654851922,
                                   'longitude': 338.1363665485192,
                                   'zodiac': {'id': 11,
                                              'lord': {'id': 5,
                                                       'name': 'Jupiter'},
                                              'name': 'Pisces'}},
                      'id': 0,
                      'number': 1,
                      'start_cusp': {'degree': 0.4464058726933331,
                                     'longitude': 300.44640587269333,
                                     'zodiac': {'id': 10,
                                                'lord': {'id': 6,
                                                         'name': 'Saturn'},
                                                'name': 'Aquarius'}}},
                     {'end_cusp': {'degree': 14.509587786159665,
                                   'longitude': 14.509587786159665,
                                   'zodiac': {'id': 0,
                                              'lord': {'id': 4, 'name': 'Mars'},
                                              'name': 'Aries'}},
                      'id': 1,
                      'number': 2,
                      'start_cusp': {'degree': 8.13636654851922,
                                     'longitude': 338.1363665485192,
                                     'zodiac': {'id': 11,
                                                'lord': {'id': 5,
                                                         'name': 'Jupiter'},
                                                'name': 'Pisces'}}},
                     {'end_cusp': {'degree': 14.92698654990852,
                                   'longitude': 44.92698654990852,
                                   'zodiac': {'id': 1,
                                              'lord': {'id': 3,
                                                       'name': 'Venus'},
                                              'name': 'Taurus'}},
                      'id': 2,
                      'number': 3,
                      'start_cusp': {'degree': 14.509587786159665,
                                     'longitude': 14.509587786159665,
                                     'zodiac': {'id': 0,
                                                'lord': {'id': 4,
                                                         'name': 'Mars'},
                                                'name': 'Aries'}}},
                     {'end_cusp': {'degree': 10.443475583530585,
                                   'longitude': 70.44347558353059,
                                   'zodiac': {'id': 2,
                                              'lord': {'id': 2,
                                                       'name': 'Mercury'},
                                              'name': 'Gemini'}},
                      'id': 3,
                      'number': 4,
                      'start_cusp': {'degree': 14.92698654990852,
                                     'longitude': 44.92698654990852,
                                     'zodiac': {'id': 1,
                                                'lord': {'id': 3,
                                                         'name': 'Venus'},
                                                'name': 'Taurus'}}},
                     {'end_cusp': {'degree': 4.314475939272825,
                                   'longitude': 94.31447593927282,
                                   'zodiac': {'id': 3,
                                              'lord': {'id': 1, 'name': 'Moon'},
                                              'name': 'Cancer'}},
                      'id': 4,
                      'number': 5,
                      'start_cusp': {'degree': 10.443475583530585,
                                     'longitude': 70.44347558353059,
                                     'zodiac': {'id': 2,
                                                'lord': {'id': 2,
                                                         'name': 'Mercury'},
                                                'name': 'Gemini'}}},
                     {'end_cusp': {'degree': 0.4464058726933331,
                                   'longitude': 120.44640587269333,
                                   'zodiac': {'id': 4,
                                              'lord': {'id': 0, 'name': 'Sun'},
                                              'name': 'Leo'}},
                      'id': 5,
                      'number': 6,
                      'start_cusp': {'degree': 4.314475939272825,
                                     'longitude': 94.31447593927282,
                                     'zodiac': {'id': 3,
                                                'lord': {'id': 1,
                                                         'name': 'Moon'},
                                                'name': 'Cancer'}}},
                     {'end_cusp': {'degree': 8.136366548519163,
                                   'longitude': 158.13636654851916,
                                   'zodiac': {'id': 5,
                                              'lord': {'id': 2,
                                                       'name': 'Mercury'},
                                              'name': 'Virgo'}},
                      'id': 6,
                      'number': 7,
                      'start_cusp': {'degree': 0.4464058726933331,
                                     'longitude': 120.44640587269333,
                                     'zodiac': {'id': 4,
                                                'lord': {'id': 0,
                                                         'name': 'Sun'},
                                                'name': 'Leo'}}},
                     {'end_cusp': {'degree': 14.50958778615967,
                                   'longitude': 194.50958778615967,
                                   'zodiac': {'id': 6,
                                              'lord': {'id': 3,
                                                       'name': 'Venus'},
                                              'name': 'Libra'}},
                      'id': 7,
                      'number': 8,
                      'start_cusp': {'degree': 8.136366548519163,
                                     'longitude': 158.13636654851916,
                                     'zodiac': {'id': 5,
                                                'lord': {'id': 2,
                                                         'name': 'Mercury'},
                                                'name': 'Virgo'}}},
                     {'end_cusp': {'degree': 14.92698654990852,
                                   'longitude': 224.92698654990852,
                                   'zodiac': {'id': 7,
                                              'lord': {'id': 4, 'name': 'Mars'},
                                              'name': 'Scorpio'}},
                      'id': 8,
                      'number': 9,
                      'start_cusp': {'degree': 14.50958778615967,
                                     'longitude': 194.50958778615967,
                                     'zodiac': {'id': 6,
                                                'lord': {'id': 3,
                                                         'name': 'Venus'},
                                                'name': 'Libra'}}},
                     {'end_cusp': {'degree': 10.443475583530557,
                                   'longitude': 250.44347558353056,
                                   'zodiac': {'id': 8,
                                              'lord': {'id': 5,
                                                       'name': 'Jupiter'},
                                              'name': 'Sagittarius'}},
                      'id': 9,
                      'number': 10,
                      'start_cusp': {'degree': 14.92698654990852,
                                     'longitude': 224.92698654990852,
                                     'zodiac': {'id': 7,
                                                'lord': {'id': 4,
                                                         'name': 'Mars'},
                                                'name': 'Scorpio'}}},
                     {'end_cusp': {'degree': 4.314475939272825,
                                   'longitude': 274.3144759392728,
                                   'zodiac': {'id': 9,
                                              'lord': {'id': 6,
                                                       'name': 'Saturn'},
                                              'name': 'Capricorn'}},
                      'id': 10,
                      'number': 11,
                      'start_cusp': {'degree': 10.443475583530557,
                                     'longitude': 250.44347558353056,
                                     'zodiac': {'id': 8,
                                                'lord': {'id': 5,
                                                         'name': 'Jupiter'},
                                                'name': 'Sagittarius'}}},
                     {'end_cusp': {'degree': 0.4464058726933331,
                                   'longitude': 300.44640587269333,
                                   'zodiac': {'id': 10,
                                              'lord': {'id': 6,
                                                       'name': 'Saturn'},
                                              'name': 'Aquarius'}},
                      'id': 11,
                      'number': 12,
                      'start_cusp': {'degree': 4.314475939272825,
                                     'longitude': 274.3144759392728,
                                     'zodiac': {'id': 9,
                                                'lord': {'id': 6,
                                                         'name': 'Saturn'},
                                                'name': 'Capricorn'}}}],
          'planet_positions': [{'degree': 10.813610810832301,
                                'house_number': 12,
                                'id': 0,
                                'is_retrograde': False,
                                'longitude': 280.8136108108323,
                                'name': 'Sun',
                                'zodiac': {'id': 9,
                                           'lord': {'id': 6, 'name': 'Saturn'},
                                           'name': 'Capricorn'}},
                               {'degree': 23.913579444554443,
                                'house_number': 12,
                                'id': 1,
                                'is_retrograde': False,
                                'longitude': 293.91357944455444,
                                'name': 'Moon',
                                'zodiac': {'id': 9,
                                           'lord': {'id': 6, 'name': 'Saturn'},
                                           'name': 'Capricorn'}},
                               {'degree': 19.869978042026503,
                                'house_number': 11,
                                'id': 2,
                                'is_retrograde': False,
                                'longitude': 259.8699780420265,
                                'name': 'Mercury',
                                'zodiac': {'id': 8,
                                           'lord': {'id': 5, 'name': 'Jupiter'},
                                           'name': 'Sagittarius'}},
                               {'degree': 27.71210950708138,
                                'house_number': 1,
                                'id': 3,
                                'is_retrograde': False,
                                'longitude': 327.7121095070814,
                                'name': 'Venus',
                                'zodiac': {'id': 10,
                                           'lord': {'id': 6, 'name': 'Saturn'},
                                           'name': 'Aquarius'}},
                               {'degree': 1.917922940168296,
                                'house_number': 7,
                                'id': 4,
                                'is_retrograde': True,
                                'longitude': 121.9179229401683,
                                'name': 'Mars',
                                'zodiac': {'id': 4,
                                           'lord': {'id': 0, 'name': 'Sun'},
                                           'name': 'Leo'}},
                               {'degree': 13.215462532613486,
                                'house_number': 5,
                                'id': 5,
                                'is_retrograde': True,
                                'longitude': 73.21546253261349,
                                'name': 'Jupiter',
                                'zodiac': {'id': 2,
                                           'lord': {'id': 2, 'name': 'Mercury'},
                                           'name': 'Gemini'}},
                               {'degree': 14.52407080829363,
                                'house_number': 2,
                                'id': 6,
                                'is_retrograde': False,
                                'longitude': 344.52407080829363,
                                'name': 'Saturn',
                                'zodiac': {'id': 11,
                                           'lord': {'id': 5, 'name': 'Jupiter'},
                                           'name': 'Pisces'}},
                               {'degree': 23.63582723772656,
                                'house_number': 4,
                                'id': 7,
                                'is_retrograde': True,
                                'longitude': 53.63582723772656,
                                'name': 'Uranus',
                                'zodiac': {'id': 1,
                                           'lord': {'id': 3, 'name': 'Venus'},
                                           'name': 'Taurus'}},
                               {'degree': 27.297824696516273,
                                'house_number': 2,
                                'id': 8,
                                'is_retrograde': False,
                                'longitude': 357.2978246965163,
                                'name': 'Neptune',
                                'zodiac': {'id': 11,
                                           'lord': {'id': 5, 'name': 'Jupiter'},
                                           'name': 'Pisces'}},
                               {'degree': 1.064801847199874,
                                'house_number': 1,
                                'id': 9,
                                'is_retrograde': False,
                                'longitude': 301.0648018471999,
                                'name': 'Pluto',
                                'zodiac': {'id': 10,
                                           'lord': {'id': 6, 'name': 'Saturn'},
                                           'name': 'Aquarius'}},
                               {'degree': 19.002769240494647,
                                'house_number': 3,
                                'id': 15,
                                'is_retrograde': False,
                                'longitude': 19.002769240494647,
                                'name': 'Chiron',
                                'zodiac': {'id': 0,
                                           'lord': {'id': 4, 'name': 'Mars'},
                                           'name': 'Aries'}},
                               {'degree': 20.56245081448992,
                                'house_number': 9,
                                'id': 105,
                                'is_retrograde': False,
                                'longitude': 200.56245081448992,
                                'name': 'Lilith',
                                'zodiac': {'id': 6,
                                           'lord': {'id': 3, 'name': 'Venus'},
                                           'name': 'Libra'}},
                               {'degree': 0.8772362286771451,
                                'house_number': 2,
                                'id': 103,
                                'is_retrograde': True,
                                'longitude': 0.8772362286771451,
                                'name': 'True North Node',
                                'zodiac': {'id': 0,
                                           'lord': {'id': 4, 'name': 'Mars'},
                                           'name': 'Aries'}},
                               {'degree': 0.877236228677134,
                                'house_number': 8,
                                'id': 104,
                                'is_retrograde': True,
                                'longitude': 180.87723622867713,
                                'name': 'True South Node',
                                'zodiac': {'id': 6,
                                           'lord': {'id': 3, 'name': 'Venus'},
                                           'name': 'Libra'}}]},
 'status': 'ok'}